### ISSUE TITLE
100% coverage

### ISSUE THREAD

**Issue by AKST** [AKST/akst.io-backend#8]
Get 100% coverage with tests

#### `Posts`
- [x] ~~`GET /post`~~
- [x] ~~`GET /post/{id}`~~
- [x] ~~`POST     /posts` #15~~
- [x] ~~`DELETE /posts/{id}` #17~~
- [x] ~~`PUT        /posts/{id}` #16~~

#### `Revisions`
- [x] ~~`GET /revisions/{id}` #18~~ 
- [x] ~~`POST     /revisions` #20~~
- [x] ~~`PUT        /revisions/{id}` #22~~

**Comment by AKST** [comment]
progress on this depends on the result of [this issue in `lab-babel`][lab-babel issue 5], _turning off coverage in the mean time_ as off 484fb6b

[lab-babel issue 5]: https://github.com/nlf/lab-babel/issues/5

**Comment by AKST** [comment]
reintroduced coverage as of c77089b

**Comment by AKST** [comment]
implemented at 43eccfe
